name: hugging_face_chat_gradio
description: "A Flutter client for interacting with Hugging Face's Chat Gradio interface."
version: 0.0.7
auther: MahmoudMagdy176203@gmail.com
homepage: https://github.com/Mahmoud-Magdy17/hugging_face_chat_gradio.git
repository: https://github.com/Mahmoud-Magdy17/hugging_face_chat_gradio.git

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0 # To make HTTP requests and stream data from Gradio

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

